name: castor_flutter_example
publish_to: 'none'
description: Example app for castor_flutter package

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  castor_flutter:
    path: ../
  dio: ^5.7.0
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true