name: castor_flutter
description: This Flutter package is a collection of widgets and utilities for building Flutter applications.
version: 1.0.2
repository: https://github.com/castorui/castor-flutter
homepage: https://castorui.github.io/castor-flutter-help/
dart3: true

environment:
  sdk: ^3.6.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.19.0 <0.21.0'
  dio: ^5.7.0
  toastification: ^1.0.0
  photo_manager: ^3.6.4
  photo_view: ^0.15.0
  # 平台插件
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# HarmonyOS 6 依赖覆盖配置
dependency_overrides:
  # 系统选择器：调用鸿蒙原生选择器和相机
  image_picker:
    git:
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      path: packages/image_picker/image_picker

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
